# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: appname_development
  host: localhost
  pool: 5
  username: psql
  password: psql

test:
  adapter: postgresql
  encoding: unicode
  database: appname_test
  host: localhost
  pool: 5
  timeout: 5000
  username: psql
  password: wrong
